### ISSUE TITLE
Configuration of the prerequisite "Risper"

### ISSUE THREAD

**Issue by 18781130375** [USFDataVisualization/Persistent-Homology-On-Time-Varying-Graphs#1]
According to the readme file, I downloaded the risper at https://github.com/Ripser/ripser.git, but has been an error in configuration. And always let me loop input "Path to ripser the executable (ripser)". What should I do about it?What should I do about it?

**Comment by PaulRosenPhD** [comment]
Make sure that you have compiled the ripser executable, as per their instructions. Then, you can reconfigure the our code (> java -jar PHTimeVaryingGraphs.jar --config) to update the paths to that executable.
